routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Authentication\RegistrationController;
use App\Http\Controllers\Authentication\AuthenticationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('dashboard.index');
});


Route::prefix('dashboard')->group(function(){
    Route::get('index',[DashboardController::class, 'Dashboard'])->name('dashboard.index');
    Route::get('reports',[DashboardController::class, 'Reports'])->name('dashboard.reports');
});

Route::resource('products', ProductsController::class);

// Route::get('login', [AuthenticationController::class, 'Login'])->name('authentication.login');
// Route::get('forgot-password', [AuthenticationController::class, 'ForgotPassword'])->name('authentication.forgot-password');
// Route::get('reset-password/{id}', [AuthenticationController::class, 'ResetPassword'])->name('authentication.reset-password');
// Route::get('logout', [AuthenticationController::class, 'Logout'])->name('authentication.logout');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    // use SoftDeletes;

    protected $table = 'product';
    protected $primaryKey = 'product_id';



    public static function List($column,$filter){
        return Product::
        leftJoin('store', 'store.store_id', '=', 'product.product_account_id')
        ->where($column,  $filter)
        ->orderBy('product.created_at', 'desc');
    }

    public static function ListPlu(){
        return Product::
        leftJoin('product_plu','product_plu.product_plu_id','=','product.product_plu_id')
        ->orderBy('product.product_id','asc');
    }

    public static function QuantityDecrease(int $product_id, int $count){
        Product::decrement('quantity', $count, array('product_id' => $product_id));
    }

    public static function ProductCost(){
        return [
            'product_selling_cost',
            'product_quantity',
            'product_cost_is_default',
        ];
    }

    public static function ProductBoolean(){
        return [

            'product_is_global',
            'product_is_online',
            'product_alert_level',
            'product_is_disabled',

        ];
    }

    public static function ProductPoints(){
        return [
            'product_points_gain',
            'product_points_collect'
        ];
    }

    public static function ProductTag(){
        return [

        ];
    }

    public static function ProductRecipe(){
        return [
            'product_recipe_text',
            'product_recipe_type',
        ];
    }

    public static function ProductPrintExclusion(){
        return [

            'product_column_name',
            'product_exclusion_type',
            //'product_exclusiontable_id',
            //'product_exclusiontable_type',
        ];
    }



    public static function ProductExclusionType(){
        return [
            'invoice',
            'receipt'
        ];
    }

    public static function ProductRecipeType(){
        return [
            'description',
            'url'
        ];
    }

    public static function ProductGrossProfit(){
        return [
           'product_target',
           'product_actual',
           'product_average_cost',
           'product_rrp'
        ];
    }

    public static function ProductSupplier(){
        return [
           'supplier_id',
           'code',
           'case_cost',
           'unit_cost'
        ];
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductPlu;

class ProductsController extends Controller
{
    private $productModel;
    private $productList;
    private $productPluList;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->productList = Product::get();

        $this->productPluList = Product::ListPlu()->get();
        // dd($this->productList[0]->product_plu);
        // dd($product_plu);
        return view('products.index',['data'=>$this->Data()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->productModel = Product::where('product_id',$id);

        return view('products.plu', ['data'=>$this->Data()]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    private function Data(){
        return [
            'productList' => $this->productList,
             'productModel' => $this->productModel,
             'productPluList' => $this->productPluList,

        ];
    }
}

resources/views/products/partial/indexPartial.blade.php
@php
use App\Models\Product;
@endphp

<div class="table-plu" uk-grid>

    <div class="uk-width-1-1">

        <table class="edit-table uk-table uk-table-small">
            <thead class="uk-text-color-secondary">
                <tr>
                    <th>PLU</th>
                    <th>Product</th>
                    <th>Price 1 L1</th>
                    <th>Price 2 L1</th>
                    <th>Price 3 L1</th>
                    <th>In Stock Qty</th>
                </tr>
            </thead>

            <tbody>
                @foreach($data['productPluList'] as $product)


                @if($product->product_id)


                @php
                    $product_prices = json_decode($product->product_std_price);
                @endphp
                <tr>
                    <td><a class="link uk-padding-small uk-padding-remove-top uk-padding-remove-bottom" href="{{ route('products.show', $product->product_id) }}" title="View Record {{ $product->product_id }}">{{ $product->product_id }}</a></td>

                    <td class="field-text"><input type="text" name="plu_{{ $product->product_id }}_name" value="{{ $product->product_name }}" readonly="readonly" maxlength="24"></td>
                    <td class="field-price">£<input class="" type="text" name="plu_{{ $product->product_id }}_price1l1" value="{{ $product_prices[0] }}" size="4" readonly="readonly"></td>
                    <td class="field-price">£<input class="" type="text" name="plu_{{ $product->product_id }}_price2l1" value="{{ $product_prices[1] }}" size="4" readonly="readonly"></td>
                    <td class="field-price">£<input class="" type="text" name="plu_{{ $product->product_id }}_price3l1" value="{{ $product_prices[2] }}" size="4" readonly="readonly"></td>
                    <td class="field-stock">-758.000</td>
                    <td></td>
                </tr>

                @endif
                @endforeach
            </tbody>
        </table>

    </div>


</div>