routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Authentication\RegistrationController;
use App\Http\Controllers\Authentication\AuthenticationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('dashboard.index');
});


Route::prefix('dashboard')->group(function(){
    Route::get('index',[DashboardController::class, 'Dashboard'])->name('dashboard.index');
    Route::get('reports',[DashboardController::class, 'Reports'])->name('dashboard.reports');
});

Route::resource('products', ProductsController::class);

// Route::get('login', [AuthenticationController::class, 'Login'])->name('authentication.login');
// Route::get('forgot-password', [AuthenticationController::class, 'ForgotPassword'])->name('authentication.forgot-password');
// Route::get('reset-password/{id}', [AuthenticationController::class, 'ResetPassword'])->name('authentication.reset-password');
// Route::get('logout', [AuthenticationController::class, 'Logout'])->name('authentication.logout');

resources/views/includes/sidebar.blade.php
<ul class="uk-nav uk-nav-default sidebar-nav">

    <li class="menu-home {{ Request::url() == route('dashboard.index') ? 'selected' : '' }}" ><a href="{{ route('dashboard.index') }}"><span class="fa fa-home uk-margin-small-right"></span> Home</a></li>
    <li class="menu-report {{ Request::url() == route('dashboard.reports') ? 'selected' : '' }}"><a href="{{ route('dashboard.reports') }}"><span class="fa fa-chart-line uk-margin-small-right"></span> Reports</a></li>
    <li class="menu-products {{ Request::url() == route('products.index') ? 'selected' : '' }}"><a href="{{ route('products.index') }}"><span class="fa fa-tag uk-margin-small-right"></span> Products</a></li>

</ul>